logo: /assets/img/sky.jpg
title: Carolyn Shi
description: This is my portfolio,
 please click below for my projects
show_downloads:
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

page1: virtualc
page2: mechaface
